spring:
  cloud:
    gateway:
      routes:
        - id: servicio-usuarios
          uri: ${URL_USERS}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2